### ISSUE TITLE
Thanks and recommended features

### ISSUE THREAD

**Issue by tahsin002** [ereb-thanatos/cossacks3-lan-server#1]
Thank you so much for bringing this game to LAN. Thank you! Thank you!
All that is left is to make a way to SAVE multiplayer games. Could you make that possible?

**Comment by ereb-thanatos** [comment]
You are welcome! I hope you enjoy the game.

Regarding your request, however, I'm afraid I can't help you. As far as I know the multiplayer save feature is not implemented in the game client yet. On another note, I am purposefully keeping the LAN server functionality to a minimum. I believe that features like ladder, rankings and saving should only be available on the official server.
