### ISSUE TITLE
Loose control over Units after time

### ISSUE THREAD

**Issue by arne-fuchs** [ereb-thanatos/cossacks3-lan-server#10]
As the title says, everyone is loosing control over their units after ~20 mins. We have the issue on Linux and Windows clients. The server runs on ubuntu 20 lts which is in the local network.

**Comment by ereb-thanatos** [comment]
Thanks for the info. Could you please provide a bit more detail:
- Which version of the **game client** has this issue?
- What exactly does happen? Are the units not accepting new orders? Can you still select them and e.g. see the progress of production in buildings? Do units start to behave as if someone else is controlling them, e.g. like the game AI?
