### ISSUE TITLE
Multiplayer saves on the latest version

### ISSUE THREAD

**Issue by endyb66** [ereb-thanatos/cossacks3-lan-server#2]
First of all, thank you so much for this really great tool, it works perfectly!
Regarding the possibility to save multiplayer games, do you think it is possible now? The game got some new updates, since another user asked this question. Back in the days, this feature was available on the old Cossacks game (Back to War) in LAN mode.

Best Regards

**Comment by ereb-thanatos** [comment]
> First of all, thank you so much for this really great tool, it works perfectly!

You are welcome!
> Regarding the possibility to save multiplayer games, do you think it is possible now?

What matters is not what I *think*, but if it's actually implemented by the game developers. Last time I checked (v2.2.3) it was not the case. Also, see #1.

Best regards
