### ISSUE TITLE
The Devs have abandoned the game, even if you haven't.

### ISSUE THREAD

**Issue by tahsin002** [ereb-thanatos/cossacks3-lan-server#5]
I am sad to say that multiplayer saves will never be a thing.
they have confirmed they won't add it. 
A game like this is played among friends, Long matches, countless hours of fun continued over days if necessary. But They did not officially make LAN nor multiplayer save. 
For years, we have asked for Multiplayer save function, but nothing was done. 
I sincerely request that you, who are passionate about the game and community, make a way to save multiplayer games. Please.

Below is what the official response is to our request. I pray with all my heart that you help us. 
Thank you.

"Hello,
Save-load functionality for multiplayer isn`t planned, but we will implement reconnections. Thanks for being interested in our game  🙂"

https://steamcommunity.com/app/333420/discussions/0/1327844097117290719/

**Comment by ereb-thanatos** [comment]
Thank you for the information. Unfortunately, I do not consider continuing this project in any way nor do I have the technical prerequisites to be able to implement such a feature in the game _client_.
