### ISSUE TITLE
Lan on Hosting

### ISSUE THREAD

**Issue by dik08razz** [ereb-thanatos/cossacks3-lan-server#9]
It seems that this is a full-fledged server, it quietly deployed on the hosting and connection to a non-native server is also without any problems

--- На случай если автор данной софтины русскоязычный --- 

Похоже, что это полноценный сервер, он спокойно развернулся на хостинге и так же без проблем происходит подключение к не родному серверу

![Screenshot_2020-04-28-01-49-07-623_com termux](https://user-images.githubusercontent.com/10263196/80431094-31aee080-88f9-11ea-94cd-48d625c51e93.jpg)

**Comment by ereb-thanatos** [comment]
Thank you for the feedback. I am glad to hear that my project is still being used. Could you please share the game client version you are using and whether you have encountered any issues so far?

P.S.: Сервер разработан только для личного пользования. Отсутствуют аутентификация, рейтинг, бейджи, турнирная лестница и другие фунцкии. Так что поднять на хостинге полноценный сервер так просто не выйдет : )

**Comment by dik08razz** [comment]
Мы с друзьями и не планировали поднимать полноценный сервер.

Одна проблема у нас была, иногда один из пяти человек отваливался.

Спасибо за подробный софт

**Comment by RazielKernel** [comment]
Hey @ereb-thanatos ! :)

Your software works flawlessly !
We're using it extensively on game version **2.2.3**.92.6008 (3EEB), OS: Windows 7 & Windows 10 machines.

We're also using your [cossacks-revamp-2017](https://github.com/ereb-thanatos/cossacks-revamp-2017) version and I gotta say... it's much better and much stable than the original !

Thanks for your work ! Sincerely appreciated !

**Comment by ereb-thanatos** [comment]
Thank you @RazielKernel, I really appreciate your feedback! Have fun with the game(s) : )
